
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonService", targetNamespace = "http://demo1.example.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CommonService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSchemaList", action = "http://demo1.example.com/GetSchemaList")
    @WebResult(partName = "return")
    public String getSchemaList();

    /**
     * 
     * @param filter
     * @param schemaCode
     * @param userCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetList", action = "http://demo1.example.com/GetList")
    @WebResult(partName = "return")
    public String getList(
        @WebParam(name = "userCode", partName = "userCode")
        String userCode,
        @WebParam(name = "schemaCode", partName = "schemaCode")
        String schemaCode,
        @WebParam(name = "filter", partName = "filter")
        String filter);

    /**
     * 
     * @param schemaCode
     * @param param
     * @param methodName
     * @param userCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Invoke", action = "http://demo1.example.com/Invoke")
    @WebResult(partName = "return")
    public String invoke(
        @WebParam(name = "userCode", partName = "userCode")
        String userCode,
        @WebParam(name = "schemaCode", partName = "schemaCode")
        String schemaCode,
        @WebParam(name = "methodName", partName = "methodName")
        String methodName,
        @WebParam(name = "param", partName = "param")
        String param);

    /**
     * 
     * @param schemaCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetSchema", action = "http://demo1.example.com/GetSchema")
    @WebResult(partName = "return")
    public String getSchema(
        @WebParam(name = "schemaCode", partName = "schemaCode")
        String schemaCode);

}
